name:                hs-server-two
version:             0.1.0.0
github:              "mkhan45/mikail-khan.com"
license:             BSD3
author:              "Mikail Khan"
maintainer:          "mikail.khan@protonmail.com"
copyright:           "Mikail Khan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mkhan45/mikail-khan.com#readme>

dependencies:
- base >= 4.7 && < 5
- blaze-html
- text
- wai
- wai-extra
- wai-middleware-static
- strict
- bytestring
- bcrypt
- warp
- warp-tls
- aeson
- htoml
- unordered-containers
- vector
- servant-server
- servant-blaze
- http-api-data

library:
  source-dirs: src

executables:
  hs-server-two-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - hs-server-two

tests:
  hs-server-two-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-server-two
