[[projects]]
projectName = "SIMple Mechanics"
projectURL = "https://github.com/mkhan45/SIMple-Mechanics"
projectThumbnail = "https://mikail-khan.com/img/mech.png"
projectDesc = "A 2D rigidbody simulator made to help learn and teach physics online."

[[projects]]
projectName = "mikail-khan.com"
projectURL = "https://github.com/mkhan45/mikail-khan.com"
projectThumbnail = "https://mikail-khan.com/img/site.png"
projectDesc = "My personal website. Built with Haskell's Servant and Blaze-HTML"

[[projects]]
projectName = "SIMple Gravity"
projectURL = "https://github.com/mkhan45/SIMple-Gravity"
projectThumbnail = "https://mikail-khan.com/img/gravity.png"
projectDesc = "A Universal Gravitation simulator made to help learn and teach physics online."

[[projects]]
projectName = "CalcuLaTeX"
projectURL = "https://calcula.tech"
projectThumbnail = "https://mikail-khan.com/img/calculatex.png"
projectDesc = "A pretty printing calculator with support for units and realtime output"

[[projects]]
projectName = "slang"
projectURL = "https://github.com/mkhan45/slang-v2"
projectThumbnail = "https://mikail-khan.com/img/slang.png"
projectDesc = "A simple scripting language interpreter"

[[projects]]
projectName = "RustScript"
projectURL = "https://github.com/mkhan45/RustScript"
projectThumbnail = "https://mikail-khan.com/img/rustscript.png"
projectDesc = "A functional scripting language with as much relation to Rust as JavaScript has to Java"

[[projects]]
projectName = "Pumice"
projectURL = "https://github.com/mkhan45/pumice"
projectThumbnail = "https://mikail-khan.com/img/pumice.png"
projectDesc = "A vulkano-made light and brittle game engine that rocks."

[[projects]]
projectName = "TinyVM"
projectURL = "https://github.com/mkhan45/tinyvm"
projectThumbnail = "https://mikail-khan.com/img/tinyvm.png"
projectDesc = "A tiny stack based bytecode VM that interprets a Turing complete instruction set."

[[projects]]
projectName = "Tetrs"
projectURL = "https://github.com/mkhan45/tetrs"
projectThumbnail = "https://mikail-khan.com/img/tetrs.png"
projectDesc = "Tetris using Rust and ggez."

[[projects]]
projectName = "ssshmup"
projectURL = "https://github.com/mkhan45/ssshmup"
projectThumbnail = "https://mikail-khan.com/img/ssshmup.png"
projectDesc = "A super small shoot 'em up"
